### ISSUE TITLE
ECONNRESET using Google Cloud Functions

### ISSUE THREAD

**Issue by emilyofficial** [desmondmorris/node-twitter#287]
`{ Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TLSWrap.onread (net.js:568:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`

Receiving the above error when trying to connect to Twitter REST API using this library on Google Cloud Functions.

I have tested on my local machine and code works great, but fails on GCF. It was working prior but stopped working overnight. Is it possible the GCF IP got banned due to excessive calls? How would I o about proving and or fixing this?

**Comment by emilyofficial** [comment]
anyone monitoring this issue tracker?
